require: rubocop-performance

AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "spec/dummy/**/*"
    - "bin/**/*"
    - "spec/tmp/**/*"
    - "lib/generators/api_guardian/install/templates/**/*"
  UseCache: false
  DisabledByDefault: true

Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Max: 120
